spinnaker:
  config:
    profiles:
      clouddriver:
        providers:
          aws:
            enabled: true
          azure:
            enabled: true
    deploymentEnvironment:
      providers:
        aws:
          enabled: true
        azure:
          enabled: true
