pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    sh 'docker build -t your-docker-registry/sample-app:latest .'
                    sh 'docker push your-docker-registry/sample-app:latest'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh './scripts/test.sh'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh './scripts/deploy.sh'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}
